"""Command-line access to the local editor API and offline idealized physics."""

import argparse
import json
import os
import sys
from pathlib import Path

from .client import APIError, DEFAULT_PORT, DEFAULT_TIMEOUT, KSPClient, ProtocolError, TransportError
from .physics import STANDARD_GRAVITY, delta_v, thrust_to_weight
from .designer import DesignError, design, write_design
from .llm import LLMError
from .gateway import GatewayModelClient
from .desktop import run_job, write_reply


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="autocraft",
        description="KSP 1.12.5 VAB/SPH localhost client. No remote load, launch, or delete operations.",
        epilog=(
            "Settings are generated by the plugin at GameData/KSPAutoCraft/PluginData/settings.json. "
            "Token precedence: --token-file, KSP_AUTOCRAFT_TOKEN, settings.json. "
            "The starter stack is a structural example only, not a flightworthiness assessment."
        ),
    )
    parser.add_argument("--ksp-root", type=Path, help="Game directory containing GameData")
    parser.add_argument("--port", type=int, help="Override the settings port (default: 18080)")
    parser.add_argument("--token-file", type=Path, help="Read a plain-text token instead of environment/settings")
    parser.add_argument("--timeout", type=float, default=DEFAULT_TIMEOUT, help="HTTP timeout in seconds, (0, 60] (default: 10)")
    commands = parser.add_subparsers(dest="command", required=True)
    commands.add_parser("health", help="Check the editor API")
    commands.add_parser("hub-health", help="Check the installed AI Hub and its model selection without inference")
    worker = commands.add_parser("desktop-worker", help="Internal one-shot worker used by the game UI")
    worker.add_argument("job", type=Path, help="Job JSON written by the game panel")
    catalog = commands.add_parser("catalog", help="Read one page of the installed part catalog")
    catalog.add_argument("--offset", type=int, default=0)
    catalog.add_argument("--limit", type=int, default=100, help="Page size, 1 to 200")
    catalog.add_argument("--search", help="Part search text (URL-encoded automatically)")
    catalog.add_argument("--output", type=Path, help="Write catalog JSON to this file instead of stdout")
    commands.add_parser("ship", help="Read the current editor ship")
    commands.add_parser("world", help="Read installed celestial bodies and save context")
    contracts = commands.add_parser("contracts", help="List current career contracts (read-only)")
    contracts.add_argument("--state", choices=("active", "offered", "all"), default="active")
    contracts.add_argument("--offset", type=int, default=0)
    contracts.add_argument("--limit", type=int, default=50)
    contract = commands.add_parser("contract", help="Read one contract's complete requirement tree")
    contract.add_argument("identifier", help="GUID from the contracts command")
    planner = commands.add_parser("design", help="Generate a natural-language/contract-grounded design through installed KSP AI Hub")
    planner.add_argument("prompt", help="Natural-language design request")
    planner.add_argument("--contract", dest="contract_id", help="Optional selected contract GUID")
    planner.add_argument("--budget", type=float, help="Hard maximum cost; also limited by current career funds")
    planner.add_argument("--max-mass", type=float, help="Hard maximum wet mass in tonnes")
    planner.add_argument("--attempts", type=int, default=3, help="Maximum generation/correction attempts, 1-3")
    planner.add_argument("--output", type=Path, required=True, help="New plan JSON filename; also writes .report.json")
    planner.add_argument("--vehicle", choices=("auto", "rocket", "aircraft"), default="auto")
    planner.add_argument("--target-altitude", type=float, help="Target altitude in metres")
    planner.add_argument("--cruise-speed", type=float, help="Aircraft cruise speed in m/s")
    planner.add_argument("--delta-v", type=float, help="Explicit rocket mission delta-v budget in m/s")
    planner.add_argument("--min-twr", type=float)
    planner.add_argument("--max-stall-speed", type=float)
    planner.add_argument("--min-endurance", type=float, help="Aircraft full-throttle fuel endurance in seconds")
    validate = commands.add_parser("validate", help="Validate a craft plan without building")
    validate.add_argument("plan", type=Path, metavar="PLAN")
    build = commands.add_parser(
        "build",
        help="Save a candidate .craft only; never loads or launches",
        description=(
            "Requires the in-game 'Allow file generation' switch. Saves a candidate .craft only. "
            "Loading is only through manual in-game GUI confirmation, with automatic backup. "
            "Builds are never automatically retried."
        ),
    )
    build.add_argument("plan", type=Path, metavar="PLAN")
    physics = commands.add_parser("physics", help="Offline ideal delta-v and TWR, not a mission assessment")
    physics.add_argument("--isp", type=float, required=True, help="Constant Isp in seconds")
    physics.add_argument("--wet", type=float, required=True, help="Wet mass in tonnes")
    physics.add_argument("--dry", type=float, required=True, help="Dry mass in tonnes")
    physics.add_argument("--thrust", type=float, required=True, help="Thrust in kN")
    physics.add_argument("--gravity", type=float, default=STANDARD_GRAVITY, help="Local gravity in m/s^2 (default: 9.80665 reference)")
    return parser


def _read_object(path: Path, label: str) -> dict:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except OSError:
        raise ValueError(f"Cannot read {label}; check the path and permissions.") from None
    except (ValueError, RecursionError):
        raise ValueError(f"{label} must contain valid UTF-8 JSON.") from None
    if not isinstance(value, dict):
        raise ValueError(f"{label} must contain a JSON object.")
    return value


def _client_from_args(args: argparse.Namespace) -> KSPClient:
    settings = {}
    if args.ksp_root is not None:
        settings_path = args.ksp_root / "GameData" / "KSPAutoCraft" / "PluginData" / "settings.json"
        if settings_path.exists():
            settings = _read_object(settings_path, "Plugin settings")
    if args.token_file is not None:
        try:
            token = args.token_file.read_text(encoding="utf-8")
        except (OSError, UnicodeError):
            raise ValueError("Cannot read the UTF-8 token file; check the path and permissions.") from None
    else:
        token = os.environ.get("KSP_AUTOCRAFT_TOKEN", settings.get("token"))
    if token is None:
        raise ValueError(
            "No API token configured. Open KSP's VAB/SPH to generate settings.json and supply --ksp-root, "
            "or set KSP_AUTOCRAFT_TOKEN or --token-file."
        )
    port = args.port if args.port is not None else settings.get("port", DEFAULT_PORT)
    if isinstance(port, bool) or not isinstance(port, int) or not 1 <= port <= 65535:
        raise ValueError("Port must be an integer from 1 to 65535.")
    return KSPClient(token, base_url=f"http://127.0.0.1:{port}", timeout=args.timeout)


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    try:
        if args.command == "physics":
            result = {
                "deltaVMetresPerSecond": delta_v(args.isp, args.wet, args.dry),
                "thrustToWeightRatio": thrust_to_weight(args.thrust, args.wet, args.gravity),
            }
        elif args.command == "hub-health":
            model = GatewayModelClient(args.ksp_root)
            model.check_ready()
            result = {"ok": True, "hubVersion": model.hub_version, "profile": model.profile, "model": model.model}
        else:
            client = _client_from_args(args)
            if args.command == "desktop-worker":
                write_reply(run_job(client, args.job, args.ksp_root))
                return 0
            elif args.command == "health":
                result = client.health()
            elif args.command == "catalog":
                result = client.catalog(offset=args.offset, limit=args.limit, search=args.search)
            elif args.command == "ship":
                result = client.ship()
            elif args.command == "world":
                result = client.world()
            elif args.command == "contracts":
                result = client.contracts(args.state, args.offset, args.limit)
            elif args.command == "contract":
                result = client.contract(args.identifier)
            elif args.command == "design":
                if args.output.exists() or args.output.with_suffix(".report.json").exists() or not args.output.parent.is_dir() or args.output.suffix.lower() != ".json":
                    raise ValueError("Choose a new .json output filename in an existing directory.")
                model = GatewayModelClient(args.ksp_root)
                model.check_ready()
                plan, report = design(client, model, args.prompt, contract_id=args.contract_id,
                                      budget=args.budget, max_mass=args.max_mass, attempts=args.attempts, vehicle=args.vehicle,
                                      target_altitude=args.target_altitude, cruise_speed=args.cruise_speed, required_delta_v=args.delta_v,
                                      min_twr=args.min_twr, max_stall_speed=args.max_stall_speed, min_endurance=args.min_endurance)
                report_path = write_design(args.output, plan, report)
                result = {"planFile": str(args.output), "reportFile": str(report_path),
                          "assessment": report["assessment"]["status"], "partCount": len(plan["parts"]),
                          "performance": report["performance"]["status"], "vehicle": report["vehicleType"],
                          "nextStep": "Review the report, then use validate/build on the plan JSON. No build was submitted automatically."}
            else:
                plan = _read_object(args.plan, "Craft plan")
                result = client.validate(plan) if args.command == "validate" else client.build(plan)
        output = json.dumps(result, indent=2, ensure_ascii=False, allow_nan=False) + "\n"
        if args.command == "catalog" and args.output is not None:
            try:
                args.output.write_text(output, encoding="utf-8")
            except OSError:
                raise ValueError("Cannot write catalog output; check the path and permissions.") from None
        else:
            sys.stdout.write(output)
        return 0
    except (APIError, TransportError, ProtocolError, DesignError, LLMError, ValueError, OSError) as error:
        if args.command == "desktop-worker":
            write_reply({"ok": False, "error": str(error)[:3000], "diagnosticFile": getattr(error, "diagnostic_file", "")})
            return 1
        print(f"error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
